import { supabase } from "./supabase";

const GLOBAL_NAMES = [
  "John Smith", "Emma Wilson", "Michael Brown", "Sophia Lee", "Yuki Tanaka", 
  "Liam O'Connor", "Olivia Chen", "Noah Williams", "Isabella Garcia", "James Johnson",
  "Lucas Martin", "Mia Anderson", "Ethan Thompson", "Ava Martinez", "Alexander White"
];

const REAL_EMAILS = [
  "gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "icloud.com"
];

// Content for different types
const STORY_CONTENT = [
  "Just arrived here! The atmosphere is amazing.",
  "Had the best coffee of my life at this small cafe.",
  "The sunset view from the tower was breathtaking.",
  "Walking around the city center at night is safe and beautiful.",
  "Finally visited the famous museum. Worth the wait!",
  "Found a hidden gem near the station. Highly recommended.",
  "The street food here is incredibly cheap and delicious.",
  "It's raining today, but the city has a different vibe.",
];

const TIP_CONTENT = [
  "Don't buy the tickets at the entrance! Book online to save 20%.",
  "Use Exit 4 for the elevator if you have heavy luggage.",
  "The best time to visit is early morning around 8 AM to avoid crowds.",
  "Make sure to carry cash, many local shops don't accept cards.",
  "You can get a free map at the tourist information center.",
  "Avoid taking the bus during rush hour (5-7 PM).",
  "Tap water is safe to drink here, bring a reusable bottle.",
  "Download the local subway app, it's much better than Google Maps here.",
];

const QNA_CONTENT = [
  "Is it safe to walk around alone at night?",
  "Can anyone recommend a good local restaurant nearby?",
  "What is the best way to get from the airport to the city center?",
  "Do I need to tip at restaurants here?",
  "Where can I buy a SIM card late at night?",
  "Is the city pass worth it for 3 days?",
  "Any recommendations for vegetarian food?",
  "How is the weather in late October?",
];

const BUDDY_CONTENT = [
  "Looking for someone to grab dinner with tonight!",
  "Anyone want to share a taxi to the airport tomorrow morning?",
  "Going to the night market. Join me!",
  "Solo traveler looking for a photography buddy for tomorrow.",
  "Planning to hike the mountain this weekend. Anyone interested?",
  "Let's go for a drink at the rooftop bar!",
  "Looking for a group to split the tour cost.",
  "Anyone in the area want to explore the old town together?",
];

const COMMENT_CONTENT = [
  "Great tip, thanks!",
  "I was wondering about this too.",
  "Totally agree with you.",
  "Can you share the location?",
  "Enjoy your trip!",
  "Be careful at night though.",
  "Wow, looks amazing!",
  "I'm going there next week!",
  "Thanks for sharing.",
  "Is it expensive?"
];

const TOUR_TITLES = [
  "Secret Night Food Tour in Osaka",
  "Bangkok Grand Palace & Temples Walking Tour",
  "Private Car Tour to Ba Na Hills, Da Nang",
  "Kyoto Tea Ceremony & Kimono Experience",
  "Taipei Night Market Street Food Challenge",
  "Stargazing Desert Adventure in Mongolia",
  "Louvre Museum Skip-the-Line Guided Tour",
  "Swiss Alps Day Trip from Zurich",
  "New York City Skyline Dinner Cruise",
  "Historical Walking Tour of Rome",
];

const COUNTRIES = ["Korea", "Japan", "Thailand", "Vietnam", "Taiwan", "USA", "France", "Italy", "Spain", "UK"];

const getRandom = (arr: any[]) => arr[Math.floor(Math.random() * arr.length)];

const generateEmail = (name: string) => {
  const domain = getRandom(REAL_EMAILS);
  const cleanName = name.toLowerCase().replace(" ", ".");
  const num = Math.floor(Math.random() * 100);
  return `${cleanName}${num}@${domain}`;
};

// 0. DB 스키마 자동 생성 (테이블 만들기)
export const initializeDB = async () => {
  const sql = `
    create table if not exists profiles (
      id uuid primary key default gen_random_uuid(),
      email text,
      name text,
      role text default 'user',
      status text default 'active',
      bio text,
      avatar_url text,
      created_at timestamp with time zone default timezone('utc'::text, now())
    );

    create table if not exists reports (
      id bigint generated by default as identity primary key,
      type text,
      content text,
      reporter text,
      flag_reason text,
      status text default 'pending',
      country text,
      created_at timestamp with time zone default timezone('utc'::text, now()),
      likes int default 0,
      parent_id bigint,
      comments_count int default 0,
      author_avatar_url text,
      user_id uuid,
      image_url text
    );

    create table if not exists tours (
      id bigint generated by default as identity primary key,
      title text,
      host text,
      price text,
      location text,
      status text default 'pending',
      image_url text,
      description text,
      created_at timestamp with time zone default timezone('utc'::text, now())
    );

    create table if not exists ads (
      id bigint generated by default as identity primary key,
      title text,
      position text,
      image_url text,
      link text,
      status text default 'active',
      clicks int default 0,
      created_at timestamp with time zone default timezone('utc'::text, now())
    );

    create table if not exists traffic (
      id bigint generated by default as identity primary key,
      path text,
      session_id text,
      created_at timestamp with time zone default timezone('utc'::text, now())
    );
    
    create table if not exists bookings (
      id bigint generated by default as identity primary key,
      user_id uuid, 
      tour_id bigint references tours(id),
      booking_date date,
      guests int default 1,
      total_price text, 
      status text default 'pending', 
      created_at timestamp with time zone default timezone('utc'::text, now())
    );
    
    create table if not exists post_likes (
      user_id uuid,
      post_id bigint,
      created_at timestamp with time zone default timezone('utc'::text, now()),
      primary key (user_id, post_id)
    );

    -- RLS policies will be managed separately for security
    -- alter table profiles disable row level security;
    -- alter table reports disable row level security;
    -- alter table tours disable row level security;
    -- alter table ads disable row level security;
    -- alter table traffic disable row level security;
    -- alter table bookings disable row level security;
    -- alter table post_likes disable row level security;
  `;

  const { error } = await supabase.rpc('exec_sql', { query: sql });
  return { success: !error, error };
};

// 1. 데이터 전체 삭제
export const clearAllData = async () => {
  await supabase.from('profiles').delete().neq('email', 'admin@spotcountry.com');
  await supabase.from('reports').delete().neq('id', 0);
  await supabase.from('tours').delete().neq('id', 0);
  await supabase.from('traffic').delete().neq('id', 0);
  await supabase.from('bookings').delete().neq('id', 0);
};

// 2. 회원 자동 생성 (글로벌)
export const generateUsers = async (count: number = 5) => {
  const users = Array.from({ length: count }).map(() => {
    const name = getRandom(GLOBAL_NAMES);
    return {
      email: generateEmail(name),
      name: name,
      role: Math.random() > 0.9 ? 'partner' : 'user',
      status: Math.random() > 0.9 ? 'banned' : 'active',
    };
  });

  const { error } = await supabase.from('profiles').upsert(users, { onConflict: 'email' });
  return { success: !error, count };
};

// 3. 신고/글 자동 생성 (다양한 타입 & 실제 댓글 생성)
export const generateReports = async (count: number = 20, live: boolean = false) => {
  // 1. 글 생성
  const posts = Array.from({ length: count }).map(() => {
    const rand = Math.random();
    let type = 'post';
    let content = "";
    
    if (rand < 0.4) {
        type = 'post'; 
        content = getRandom(STORY_CONTENT);
    } else if (rand < 0.6) {
        type = 'tip'; 
        content = getRandom(TIP_CONTENT);
    } else if (rand < 0.8) {
        type = 'qna'; 
        content = getRandom(QNA_CONTENT);
    } else {
        type = 'buddy'; 
        content = getRandom(BUDDY_CONTENT);
    }

    return {
      type: type,
      content: content,
      reporter: getRandom(GLOBAL_NAMES),
      flag_reason: null, // Live posts shouldn't be flagged usually
      status: 'approved',
      country: getRandom(COUNTRIES),
      likes: Math.floor(Math.random() * 10), // Start with fewer likes for new posts
      comments_count: 0,
      created_at: live ? new Date().toISOString() : new Date(Date.now() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000)).toISOString()
    };
  });

  const { data: insertedPosts, error } = await supabase.from('reports').insert(posts).select();
  
  if (error || !insertedPosts) return { success: false, count: 0 };

  // 2. 각 글마다 랜덤 댓글 생성
  let totalComments = 0;
  for (const post of insertedPosts) {
    const commentCount = Math.floor(Math.random() * 6); // 0~5 comments
    if (commentCount > 0) {
        const comments = Array.from({ length: commentCount }).map(() => ({
            type: 'comment',
            content: getRandom(COMMENT_CONTENT),
            reporter: getRandom(GLOBAL_NAMES),
            parent_id: post.id, 
            country: post.country,
            status: 'approved',
            created_at: live ? new Date(Date.now() + 1000 * 60).toISOString() : new Date(Date.now() - Math.floor(Math.random() * 3 * 24 * 60 * 60 * 1000)).toISOString() // Comments slightly after
        }));

        await supabase.from('reports').insert(comments);
        
        await supabase.from('reports').update({ comments_count: commentCount }).eq('id', post.id);
        totalComments += commentCount;
    }
  }

  return { success: true, count: count + totalComments };
};

// 4. 투어 자동 생성 (영어)
export const generateTours = async (count: number = 3) => {
  const tours = Array.from({ length: count }).map(() => ({
    title: getRandom(TOUR_TITLES),
    host: `${getRandom(GLOBAL_NAMES)}`,
    price: `$${Math.floor(Math.random() * 100) + 20}`,
    location: getRandom(COUNTRIES),
    status: Math.random() > 0.7 ? 'approved' : 'pending',
    description: "Experience the best of local culture with our guided tour. Includes transportation and lunch.",
  }));

  const { error } = await supabase.from('tours').insert(tours);
  return { success: !error, count };
};

// 5. 전체 리셋 및 시뮬레이션
export const resetAndSeed = async () => {
  await clearAllData();
  await generateUsers(15);
  await generateReports(30); 
  await generateTours(8);
  return { success: true };
};
