import { createClient } from '@supabase/supabase-js';

// Load Env
const supabaseUrl = 'https://kfqnxmxgwhazmzbbvbbr.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmcW54bXhnd2hhem16YmJ2YmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMjI1NjcsImV4cCI6MjA4Njg5ODU2N30.VXIGgl5wCyTC6s5jj61PzqbsDr2ezbX-M5ljJVl7bnY';

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const createBookingsTable = async () => {
  const sql = `
    -- Create bookings table
    create table if not exists bookings (
      id bigint generated by default as identity primary key,
      user_id uuid, -- Link to auth user
      tour_id bigint references tours(id),
      booking_date date,
      guests int default 1,
      total_price text, -- Store as text to match tour price format '$100' or numeric if needed. Let's assume text for MVP simplicity
      status text default 'pending', -- pending, confirmed, cancelled
      created_at timestamp with time zone default timezone('utc'::text, now())
    );
    
    -- Disable RLS for now
    alter table bookings disable row level security;
  `;

  console.log("Creating bookings table...");
  const { error } = await supabase.rpc('exec_sql', { query: sql });
  
  if (error) {
    console.error("Error creating bookings table:", error);
  } else {
    console.log("Schema updated! 'bookings' table created.");
  }
};

createBookingsTable();
